package com.iclp.windowmanager.demo;

import com.iclp.windowmanager.Desktop;
import com.iclp.windowmanager.DesktopCanvas;
import com.iclp.windowmanager.Manager;
import com.iclp.windowmanager.Rectangle;
import com.iclp.windowmanager.Renderer;
import com.iclp.windowmanager.Window;
import com.sun.media.jfxmedia.logging.Logger;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.GridLayout;
import javax.swing.DefaultListModel;

public class DemoGUI extends javax.swing.JFrame 
{
    private Manager manager;

    /**
     * Creates new form DemoGUI
     */
    public DemoGUI() 
    {
        this.manager = new Manager(4);
        
        class TestWindow extends Window
        {

            public TestWindow(Manager manager, Desktop desktop, String title,int width, int height) {
                super(manager, desktop, title, width, height);
            }

            @Override
            public void run()
            {
                int x = 0, y = getHeight() / 2;
                
                while(true)
                {
                    if(x < getWidth())
                    {
                        ++x;
                    }
                    else
                    {
                        x = 0;
                    }
                    
                    //setRectangle(new Rectangle(x, 0, getWidth(), getHeight()));
                    
                    Graphics2D g2 = getBuffer().beginRender();
                    
                    g2.setColor(Color.WHITE);
                    g2.fillRect(0, 0, getWidth(), getHeight());
                    
                    g2.setColor(Color.RED);
                    g2.drawString("Hello World!", x, y);
                    
                    g2.dispose();
                    
                    getBuffer().endRender(g2);
                    
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
            }
        }

        Desktop desktop1 = new Desktop(this.manager, "Desktop1", Color.GREEN, 700, 500);
        Desktop desktop2 = new Desktop(this.manager, "Desktop2", Color.ORANGE, 700, 500);
        
        Window window1 = new TestWindow(this.manager, desktop1, "Window 1", 300, 200);
        window1.start();
        Window window2 = new TestWindow(this.manager, desktop2, "Window 2", 300, 200);
        window2.start();
        Window window3 = new TestWindow(this.manager, desktop2, "Window 3", 300, 200);
        window3.setRectangle(new Rectangle(50, 50, 300, 200));
        window3.start();
        
        initComponents();
        
        lblFirstDesktop.setText(desktop1.getName());
        lblSecondDesktop.setText(desktop2.getName());
        
        DefaultListModel<String> model = new DefaultListModel<String>();
        listFirstWindows.setModel(model);
        for(Window window : manager.getWindows(desktop1))
        {
            model.addElement(window.getTitle());
        }
        
        model = new DefaultListModel<String>();
        listSecondWindows.setModel(model);
        for(Window window : manager.getWindows(desktop2))
        {
            model.addElement(window.getTitle());
        }
        
        canvasPanel.setLayout(new GridLayout(1, 0));
        Renderer renderer = new Renderer(manager, 30);
        for(DesktopCanvas desktopCanvas : renderer.getCanvases())
        {
            canvasPanel.add(desktopCanvas);
        }
        renderer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvasPanel = new javax.swing.JPanel();
        lblFirstDesktop = new javax.swing.JLabel();
        lblSecondDesktop = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFirstWindows = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSecondWindows = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1400, 699));

        javax.swing.GroupLayout canvasPanelLayout = new javax.swing.GroupLayout(canvasPanel);
        canvasPanel.setLayout(canvasPanelLayout);
        canvasPanelLayout.setHorizontalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        canvasPanelLayout.setVerticalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        lblFirstDesktop.setText("jLabel1");

        lblSecondDesktop.setText("jLabel1");

        listFirstWindows.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listFirstWindowsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listFirstWindows);

        jScrollPane2.setViewportView(listSecondWindows);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(lblFirstDesktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSecondDesktop)
                .addGap(321, 321, 321))
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(canvasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstDesktop)
                    .addComponent(lblSecondDesktop))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(333, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listFirstWindowsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listFirstWindowsValueChanged
        manager.getLogger().log(Logger.DEBUG, listFirstWindows.getSelectedValue().toString());
    }//GEN-LAST:event_listFirstWindowsValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFirstDesktop;
    private javax.swing.JLabel lblSecondDesktop;
    private javax.swing.JList<String> listFirstWindows;
    private javax.swing.JList<String> listSecondWindows;
    // End of variables declaration//GEN-END:variables
}
