package com.iclp.windowmanager.demo;

import com.iclp.windowmanager.Desktop;
import com.iclp.windowmanager.DesktopCanvas;
import com.iclp.windowmanager.Manager;
import com.iclp.windowmanager.Rectangle;
import com.iclp.windowmanager.Renderer;
import com.iclp.windowmanager.Window;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.GridLayout;

public class DemoGUI extends javax.swing.JFrame 
{
    private Manager manager;

    /**
     * Creates new form DemoGUI
     */
    public DemoGUI() 
    {
        this.manager = new Manager(4);
        
        class TestWindow extends Window
        {

            public TestWindow(Manager manager, Desktop desktop, String title,int width, int height) {
                super(manager, desktop, title, width, height);
            }

            @Override
            public void run()
            {
                int x = 0, y = getHeight() / 2;
                
                while(true)
                {
                    if(x < getWidth())
                    {
                        ++x;
                    }
                    else
                    {
                        x = 0;
                    }
                    
                    //setRectangle(new Rectangle(x, 0, getWidth(), getHeight()));
                    
                    Graphics2D g2 = getBuffer().beginRender();
                    
                    g2.setColor(Color.WHITE);
                    g2.fillRect(0, 0, getWidth(), getHeight());
                    
                    g2.setColor(Color.RED);
                    g2.drawString("Hello World!", x, y);
                    
                    g2.dispose();
                    
                    getBuffer().endRender(g2);
                    
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
            }
        }

        Desktop desktop1 = new Desktop(this.manager, "Desktop1", Color.GREEN, 700, 500);
        Desktop desktop2 = new Desktop(this.manager, "Desktop2", Color.ORANGE, 700, 500);
        
        Window window1 = new TestWindow(this.manager, desktop1, "Window 1", 300, 200);
        window1.start();
        Window window2 = new TestWindow(this.manager, desktop2, "Window 2", 300, 200);
        window2.start();
        Window window3 = new TestWindow(this.manager, desktop2, "Window 3", 300, 200);
        window3.setRectangle(new Rectangle(50, 50, 300, 200));
        window3.start();
        
        initComponents();
        
        canvasPanel.setLayout(new GridLayout(1, 0));
        Renderer renderer = new Renderer(manager, 30);
        for(DesktopCanvas desktopCanvas : renderer.getCanvases())
        {
            canvasPanel.add(desktopCanvas);
        }
        renderer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvasPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout canvasPanelLayout = new javax.swing.GroupLayout(canvasPanel);
        canvasPanel.setLayout(canvasPanelLayout);
        canvasPanelLayout.setHorizontalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        canvasPanelLayout.setVerticalGroup(
            canvasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(canvasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addComponent(jLabel1)
                .addContainerGap(1005, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(canvasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(0, 376, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DemoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canvasPanel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
